// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL9h9hoOsPR_bGwbr8cLGD0EgCJc8dVvs',
    appId: '1:197289920803:web:9eebda92dbfe09919be496',
    messagingSenderId: '197289920803',
    projectId: 'fir-notificationdemo-c6f9b',
    authDomain: 'fir-notificationdemo-c6f9b.firebaseapp.com',
    databaseURL: 'https://fir-notificationdemo-c6f9b.firebaseio.com',
    storageBucket: 'fir-notificationdemo-c6f9b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9P7SfnY1rYmxMWPyKMc5vYfVBa2rmJns',
    appId: '1:197289920803:android:f899382598c0634e9be496',
    messagingSenderId: '197289920803',
    projectId: 'fir-notificationdemo-c6f9b',
    databaseURL: 'https://fir-notificationdemo-c6f9b.firebaseio.com',
    storageBucket: 'fir-notificationdemo-c6f9b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCY40nWQy3xAAlQaQPX7BCvj14M2VvgmLc',
    appId: '1:197289920803:ios:0259b82688d198579be496',
    messagingSenderId: '197289920803',
    projectId: 'fir-notificationdemo-c6f9b',
    databaseURL: 'https://fir-notificationdemo-c6f9b.firebaseio.com',
    storageBucket: 'fir-notificationdemo-c6f9b.appspot.com',
    androidClientId: '197289920803-95rqi1pt634q1182jrgo6haflti09s0j.apps.googleusercontent.com',
    iosClientId: '197289920803-66q0a7h6eond6j5754a91tnlb94e0gi5.apps.googleusercontent.com',
    iosBundleId: 'com.example.gmai',
  );
}
